### 
# GET /ressources
GET http://localhost:3000/ressources
Content-Type: application/json
###

### 
# GET /ressources/:id
GET http://localhost:3000/ressources/3
Content-Type: application/json
###

### 
# POST /ressources
POST http://localhost:3000/ressources
Content-Type: application/json

{
    "title": "Nouvelle ressource",
    "description": "Description de la nouvelle ressource",
    "id_app_user": 1
}
###

### 
# PATCH /ressources/:id
PATCH http://localhost:3000/ressources/7
Content-Type: application/json

{
    "title": "Nouveau titre de la nouvelle ressource",
    "description": "Nouvelle description de la nouvelle ressource"
}
###

###
# DELETE /ressources/:id
DELETE http://localhost:3000/ressources/7
###